.\" crash-command: cpu
.\" crash-symbol: help_cpu
.TH CRASH-CPU 8
.SH NAME
crash-cpu \- set context to the active task on a cpu
.SH SYNOPSIS
.B cpu
[cpu]
.SH DESCRIPTION
.PP
This command sets the current context to the active task on a cpu.  If no
argument is given, the current context is displayed.
.nf
    cpu   a valid cpu number
.fi
.PP
This command is not allowable on live systems.
.SH EXAMPLES
.nf
    crash> cpu 1
         PID: 286
     COMMAND: "in.rlogind"
        TASK: c0b3a000
         CPU: 1
       STATE: TASK_RUNNING (ACTIVE)
.fi
.SH SEE ALSO
.BR crash (8)
