.\" crash-command: waitq
.\" crash-symbol: help_waitq
.TH CRASH-WAITQ 8
.SH NAME
crash-waitq \- list tasks queued on a wait queue
.SH SYNOPSIS
.B waitq
[ symbol ] | [ struct.member struct_addr ] | [ address ]
.SH DESCRIPTION
.PP
This command walks the wait queue list displaying the tasks which
are blocked on the specified wait queue.  The command differentiates
between the old- and new-style wait queue structures used by the kernel.
It can be invoked with the following argument types:
.nf
                     symbol  a global symbol of a wait queue.
.fi
.PP
struct.member struct_addr  a structure name and wait queue member combination
.nf
                             followed by the structure's hexadecimal address.
                    address  a hexadecimal wait queue pointer.
.fi
.SH EXAMPLES
.PP
Find out if any tasks are blocked on the "buffer_wait" wait queue:
.nf
    crash> waitq buffer_wait
    wait queue "buffer_wait" (c02927f0) is empty
.fi
.PP
See who is blocked on the "wait_chldexit" queue of task c5496000:
.nf
    crash> waitq task_struct.wait_chldexit c5496000
    PID: 30879  TASK: c5496000  CPU: 0   COMMAND: "bash"
.fi
.PP
Display the task list waiting on a known task queue:
.nf
    crash> waitq c3534098
    PID: 13691  TASK: c3534000  CPU: 1   COMMAND: "bash"
.fi
.SH SEE ALSO
.BR crash (8)
