.\" crash-command: echo
.\" crash-symbol: help_echo
.\" crash-include: extensions/echo_help.h
.TH CRASH-ECHO 8
.SH NAME
crash-echo \- echoes back its arguments
.SH SYNOPSIS
.in 0
.nf
echo arg ...
.fi
.in
.SH DESCRIPTION
.in 0
.nf
  This command simply echoes back its arguments.
.fi
.in
.SH EXAMPLES
.in 0
.nf
  Echo back all command arguments:

    crash> echo hello, world
    hello, world
.fi
.in
