.\" crash-command: snap
.\" crash-symbol: help_snap
.\" crash-include: extensions/snap_help.h
.TH CRASH-SNAP 8
.SH NAME
crash-snap \- take a memory snapshot
.SH SYNOPSIS
.in 0
.nf
snap [-n] dumpfile
.fi
.in
.SH DESCRIPTION
.in 0
.nf
  This command takes a snapshot of physical memory and creates an ELF vmcore.
  The default vmcore is a kdump-style dumpfile.  Supported on x86, x86_64,
  ia64 and ppc64 architectures only.
 
    -n  create a netdump-style vmcore (n/a on x86_64).
.fi
.in
