.\" crash-command: s390dbf
.\" crash-symbol: help_s390dbf
.TH CRASH-S390DBF 8
.SH NAME
crash-s390dbf \- s390dbf prints out debug feature logs
.SH SYNOPSIS
.B s390dbf
[-v] [-s dirname] [debug log] [debug view]
.SH DESCRIPTION
.PP
Display Debug logs:
+ If called without parameters, all active debug logs are listed.
+ If called with the name of a debug log, all debug-views for which
.nf
   the debug-log has registered are listed. It is possible thatsome
   of the debug views are not available to 'crash'.
.fi
.PP
+ If called with the name of a debug-log and an available viewname,
.nf
   the specified view is printed.
.fi
.PP
+ If called with '-s dirname', the s390dbf is saved to the specified
.nf
   directory
.fi
.PP
+ If called with '-v', all debug views which are available to
.nf
   'crash' are listed
.fi
.SH SEE ALSO
.BR crash (8)
