.\" crash-command: snap
.\" crash-symbol: help_snap
.\" crash-include: extensions/snap_help.h
.TH CRASH-SNAP 8
.SH NAME
crash-snap \- take a memory snapshot
.SH SYNOPSIS
.B snap
[-n] dumpfile
.SH DESCRIPTION
.PP
This command takes a snapshot of physical memory and creates an ELF vmcore.
The default vmcore is a kdump-style dumpfile.  Supported on x86, x86_64,
ia64 and ppc64 architectures only.
.TP
.BI \-n
create a netdump-style vmcore (n/a on x86_64).
.SH SEE ALSO
.BR crash (8)
