.\" crash-command: ptov
.\" crash-symbol: help_ptov
.TH CRASH-PTOV 8
.SH NAME
crash-ptov \- physical to virtual
         per-cpu to virtual
.SH SYNOPSIS
.B ptov
[address | offset:cpuspec]
.SH DESCRIPTION
.PP
This command translates a hexadecimal physical address into a kernel
virtual address.  Alternatively, a hexadecimal per-cpu offset and
cpu specifier will be translated into kernel virtual addresses for
each cpu specified.
.nf
         address  a physical address
.fi
.PP
offset:cpuspec  a per-cpu offset with a CPU specifier:
.nf
                    :             CPU of the currently selected task.
                    :a[ll]        all CPUs.
                    :#[-#][,...]  CPU list(s), e.g. "1,3,5", "1-3",
                                or "1,3,5-7,10".
.fi
.SH EXAMPLES
.PP
Translate physical address 56e000 into a kernel virtual address:
.nf
    crash> ptov 56e000
.fi
.PP
.B VIRTUAL           PHYSICAL
.nf
    ffff88000056e000  56e000
.fi
.PP
Translate per-cpu offset b0c0 into a kernel virtual address for
all cpus:
.nf
    crash> ptov b0c0:a
    PER-CPU OFFSET: b0c0
.fi
.PP
.B CPU    VIRTUAL
.nf
      [0]  ffff88021e20b0c0
      [1]  ffff88021e24b0c0
      [2]  ffff88021e28b0c0
      [3]  ffff88021e2cb0c0
.fi
.SH SEE ALSO
.BR crash (8)
