.\" crash-command: btop
.\" crash-symbol: help_btop
.TH CRASH-BTOP 8
.SH NAME
crash-btop \- bytes to page
.SH SYNOPSIS
.B btop
address ...
.SH DESCRIPTION
.PP
This command translates a hexadecimal address to its page number.
.SH EXAMPLES
.nf
    crash> btop 512a000
    512a000: 512a
.fi
.SH SEE ALSO
.BR crash (8)
