.\" crash-command: wr
.\" crash-symbol: help_wr
.TH CRASH-WR 8
.SH NAME
crash-wr \- write memory
.SH SYNOPSIS
.B wr
[-u|-k|-p] [-8|-16|-32|-64] [address|symbol] value
.SH DESCRIPTION
.PP
This command modifies the contents of memory.  The starting address may be
entered either symbolically or by address.  The default modification size
is the size of a long data type.  Write permission must exist on the
/dev/mem.  When writing to memory on a live system, this command should
obviously be used with great care.
.TP
.BI \-u
address argument is a user virtual address.
.TP
.BI \-k
address argument is a kernel virtual address.
.TP
.BI \-p
address argument is a physical address.
.TP
.BI \-8
write data in an 8-bit value.
.TP
.BI \-16
write data in a 16-bit value.
.TP
.BI \-32
write data in a 32-bit values (default on 32-bit machines).
.TP
.BI \-64
write data in a 64-bit values (default on 64-bit machines).
.PP
address  address to write.  The address is considered virtual unless the
.TP
.BI \-p \ option \ is \ used.
If a virtual address is specified, the
.TP
.BI \-u \ or \ \-k \ options \ are \ necessary \ only \ if \ the \ address \ space \ cannot
.nf
           be determined from the address value itself.  If a user virtual
           address is specified, the address space of the current context
           implied.  The address must be expressed in hexadecimal format.
   symbol  symbol of starting address to write.
    value  the value of the data to write.
.fi
.SH EXAMPLES
.PP
Turn on a debug flag:
.nf
    crash> wr my_debug_flag 1
.fi
.SH SEE ALSO
.BR crash (8)
