.\" crash-command: rustfilt
.\" crash-symbol: help_rustfilt
.TH CRASH-RUSTFILT 8
.SH NAME
crash-rustfilt \- demangle a mangled Rust symbol to human readable symbol
.SH SYNOPSIS
.in 0
.nf
rustfilt <symbol>
.fi
.in
.SH DESCRIPTION
.in 0
.nf
  This command converts a mangled Rust symbol to human readable symbol.
.fi
.in
.SH EXAMPLES
.in 0
.nf
  crash> rustfilt _RNvNtCshc5sK6KjdJJ_6kernel5print11call_printk
  kernel::print::call_printk
.fi
.in
