.\" crash-command: rustfilt
.\" crash-symbol: help_rustfilt
.TH CRASH-RUSTFILT 8
.SH NAME
crash-rustfilt \- demangle a mangled Rust symbol to human readable symbol
.SH SYNOPSIS
.B rustfilt
<symbol>
.SH DESCRIPTION
.PP
This command converts a mangled Rust symbol to human readable symbol.
.SH EXAMPLES
.PP
crash> rustfilt _RNvNtCshc5sK6KjdJJ_6kernel5print11call_printk
kernel::print::call_printk
.SH SEE ALSO
.BR crash (8)
