.\" crash-command: echo
.\" crash-symbol: help_echo
.\" crash-include: extensions/echo_help.h
.TH CRASH-ECHO 8
.SH NAME
crash-echo \- echoes back its arguments
.SH SYNOPSIS
.B echo
arg ...
.SH DESCRIPTION
.PP
This command simply echoes back its arguments.
.SH EXAMPLES
.PP
Echo back all command arguments:
.nf
    crash> echo hello, world
    hello, world
.fi
.SH SEE ALSO
.BR crash (8)
