.\" crash-command: ptob
.\" crash-symbol: help_ptob
.TH CRASH-PTOB 8
.SH NAME
crash-ptob \- page to bytes
.SH SYNOPSIS
.B ptob
page_number ...
.SH DESCRIPTION
.PP
This command translates a page frame number to its byte value.
.SH EXAMPLES
.nf
    crash> ptob 512a
    512a: 512a000
.fi
.SH SEE ALSO
.BR crash (8)
